# Generated by Django 6.0.1 on 2026-04-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('PROVIDER', 'Provider')], default='customer', max_length=20),
        ),
    ]
