# Generated by Django 6.0.1 on 2026-04-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('provider', 'Provider')], default='customer', max_length=20),
        ),
    ]
